Finished Google Homepage
smeetthakkar/google-hompage pull request #1
Opened 2020-04-30 13:41 UTC by smeetthakkar

2020-04-30 14:43 UTC, spwr007 reviewed
@smeetthakkar Reviewed

2020-04-30 14:43 UTC, spwr007 commented on README.md
> +<ul>
https://guides.github.com/features/mastering-markdown/

2020-04-30 14:43 UTC, spwr007 commented on index.html
> +    <title>Google</title>
Use 2 tab spaces

2020-04-30 14:43 UTC, spwr007 commented on index.html
> +            <img src="resources/images/logo.png" alt="company logo" class="company-logo">
best practise, void elemnts should be self closed, img, input, br, etc, etc

2020-04-30 14:43 UTC, spwr007 commented on index.html
> +        <center>
mostly avoid styling from tags, such as center, b, i, tag, dont use styling tags.
keep structure and styling separate.

2020-04-30 14:43 UTC, spwr007 commented on index.html
> +                    <input type="submit" value="I'm Feeling Lucky">
input tags are form elements, should be used in form, without form no submit actions.
use button tags instead or input type button

2020-04-30 14:43 UTC, spwr007 commented on index.html
> +        <div class="fbar">
Indentation

2020-04-30 14:43 UTC, spwr007 commented on resources/style.css
> +    margin: 0;
2 tab spaces

2020-04-30 14:43 UTC, spwr007 commented on resources/style.css
> +}
use reset css, recommended.

2020-04-30 14:43 UTC, spwr007 commented on resources/style.css
> +.cta input[type="submit"] {
i believe there are only two inputs ;p.

type= 'submit' not needed

2020-04-30 14:43 UTC, spwr007 commented on resources/style.css
> +.fbar {
keep one liner, when block contains only one css prop

2020-04-30 14:43 UTC, spwr007 commented on resources/style.css
> +}
put an endline

2020-04-30 19:38 UTC, vishalsg42 requested changes

2020-04-30 19:38 UTC, vishalsg42 commented on index.html
> +                    <li>Advertising</li>
This should be clickeable. add anchor tag

2020-04-30 19:38 UTC, vishalsg42 commented on resources/style.css
> +
add comments  for each section as you design

2020-04-30 19:38 UTC, vishalsg42 commented on index.html
> +<!DOCTYPE html>
I understand you have committed all the files once. but try to start the project with git. Also, keep committing codes frequently as when you complete each section.

2020-04-30 19:38 UTC, vishalsg42 commented on index.html
> +                    <input type="text" id="searchbox" name="searchbox" class="input-field">
```
<form>
For wrapping form element  use **form-group** classname
  <div class="form-group">
For input tags or form elems use **form-control** classname
       <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
Submit button should not be wrapped. 
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
```

2020-05-06 11:05 UTC, smeetthakkar commented on README.md
> +<ul>
Noted. Thanks for sharing, I'll review and update. The new commit focuses on code related changes, will update the README.md in the next iteration.

2020-05-06 11:06 UTC, smeetthakkar commented on index.html
> +            <img src="resources/images/logo.png" alt="company logo" class="company-logo">
Done.

2020-05-06 11:06 UTC, smeetthakkar commented on index.html
> +        <center>
Noted. Thanks!

2020-05-06 11:07 UTC, smeetthakkar commented on index.html
> +                    <input type="submit" value="I'm Feeling Lucky">
Implemented.

2020-05-06 11:07 UTC, smeetthakkar commented on resources/style.css
> +    margin: 0;
Updated css files.

2020-05-06 11:08 UTC, smeetthakkar commented on resources/style.css
> +}
My initial understanding was * {margin: 0, padding: 0, box-sizing: border-box; } resets CSS, however, I have researched a different approach, lmk if that meets your expectations?

2020-05-06 11:08 UTC, smeetthakkar commented on resources/style.css
> +.cta input[type="submit"] {
Haha, coolness ha! Thanks for the tip though!

2020-05-06 11:08 UTC, smeetthakkar commented on resources/style.css
> +.fbar {
Implemented.

2020-05-06 11:09 UTC, smeetthakkar commented on resources/style.css
> +}
Implemented.

2020-05-06 11:09 UTC, smeetthakkar commented on index.html
> +                    <li>Advertising</li>
Implemented.

2020-05-06 11:09 UTC, smeetthakkar commented on resources/style.css
> +
Makes total sense, thanks, will keep that in mind in future projects.

2020-05-06 11:11 UTC, smeetthakkar commented on index.html
> +<!DOCTYPE html>
Got it. And, you're right, I agree, having an initial commit on master and then resorting to branches is a good approach. Thanks for the tip!

2020-05-06 11:11 UTC, smeetthakkar commented on index.html
> +                    <input type="text" id="searchbox" name="searchbox" class="input-field">
Sounds good. I've updated the approach but when I use forms in the future, I'll keep this in mind, thank you!

2020-05-06 11:18 UTC, smeetthakkar commented
@vishalsg42 @spwr007 Hi folks! Firstly, thanks a ton for the review!

I've addressed all your comments, please review and lmk your thoughts. FYI, I've update the approach. This means, the markup and styles were rewritten. I've included details in the commit message and the files for your perusal. Even added a tag on the previous commit just in case. 

@spwr007 I need to update the markdown for README.md, that's the only thing remaining. I'll take that up during the next iteration sometime this week. Will keep you posted. Thanks for sharing the resource.

2020-05-06 16:56 UTC, smeetthakkar reviewed
All changes reviewed/implemented, please check.

2020-05-07 18:18 UTC, vishalsg42 approved these changes

2020-05-07 18:18 UTC, vishalsg42 commented on resources/style.css
> +}
Have a look over this link: [reset css]( https://meyerweb.com/eric/tools/css/reset/)

2020-05-10 14:03 UTC, spwr007 commented on resources/style.css
> +}
Reset CSS is not only for styling properties, but to maintain the styling along with units across browsers.
The above line does work but not perfectly for all tags. Follow reset css.

2020-05-21 10:04 UTC, smeetthakkar commented on resources/style.css
> +}
Understood. Vishal shared a link, been using that as well.

2020-05-21 10:05 UTC, smeetthakkar commented on README.md
> +<ul>
This is fixed as well. I updated the readme.md file.

2020-05-21 10:06 UTC, merged